@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODQ2MGVhZGU5MzIzYjRlMTY0NWJmOCIsImVtYWlsIjoic2FqaXZAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzcwMzU3ODgyLCJhdWQiOiJyYnMtZ3JvY2VyeS11c2VycyIsImlzcyI6InJicy1ncm9jZXJ5LWFwcCJ9.e9-V2k4JE72mi9mxlYEgRG-1cwJ-v4oWaJFTfdLeYgI
@url =  https://4vx2jv62-5000.inc1.devtunnels.ms/api

# 
post {{url}}/auth/register
Content-type: application/json

{
  "firstName": "Sahil",
  "lastName": "Joya",
  "email": "sahil.joya@example.com",
  "password": "Sahil@123",
  "phone": "9876543210"
}

############
# login user
post {{url}}/auth/login
Content-type: application/json

{
    "email":"sajiv@gmail.com",
    "password":"12345678"
}

############
# Profile
GET  {{url}}/auth/profile
Content-type: application/json
Authorization: {{token}}



############
# updateProfile
PUT  {{url}}/auth/updateProfile
Content-type: application/json
Authorization: {{token}}

{
  "firstName":"Sajiv",
  "lastName":"Ansari",
  "phone":"9508937828",
  "address":{
    "street":"Jhotwara",
    "city":"Jaipur",
    "state":"Rajsthan",
    "zipCode":"302012",
    "country":"India"
  }
}
############
# changePassword
PUT  {{url}}/auth/changePassword
Content-type: application/json
Authorization: {{token}}

{
  "newPassword":"123456",
  "currentPassword":"321654"
}


############
# products
GET {{url}}/user/products?category=&search=&page=1&limit=20
Content-Type: application/json

############
# products get by id
GET   {{url}}/user/products/getById?id=6981d3fc70067af2d5ec90ff
Content-type: application/json

############
# subscription
POST  {{url}}/user/subscription/create
Content-Type: application/json
Authorization: {{token}}

{
  "productId": "65f1c9a2b8f7c12345678901",
  "quantity": 2,
  "frequency": "DAILY",
  "startDate": "2026-02-10",
}


############
# toggleSubscription
POST  {{url}}/user/toggleSubscription
Content-Type: application/json
Authorization: {{token}}

{
  "id":"65f1c9a2b8f7c12345678901"
}


############
# checkSubscription
GET {{url}}/user/checkSubscription?productId=65f1c9a2b8f7c12345678901
Content-Type: application/json
Authorization: {{token}}

############
# subscriptionProducts
GET {{url}}/user/subscriptionProducts
Content-Type: application/json
Authorization: {{token}}

############
# contact us query
POST  {{url}}/user/contactForm
Content-Type: application/json

{
  "name":"sajivddin",
  "email":"sajiv@gamil.com",
   "queryType":"order issues",
   "subject":"order nhi ho rha hai ",
   "message":"help karo order nhi ho rha hai "
}