@url =  http://192.168.1.43:5000/api

# 
post {{url}}/auth/register
Content-type: application/json

{
  "firstName": "Sahil",
  "lastName": "Joya",
  "email": "sahil.joya@example.com",
  "password": "Sahil@123",
  "phone": "9876543210"
}

############
# login user
post {{url}}/auth/login
Content-type: application/json

{
    "email":"dem@gmail.co",
    "password":"12345678"
}